### ISSUE TITLE
ENMeval fails to run: <Error in x[[1]] : subscript out of bounds>

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#11]
I've opened this issue as it's own issue. I think to solve this we need to address how to access worldclim data. I'd like feedback from each of you on this one.

1. We could package it with the repo, most likely as R rasterStack objects. These may be very large files though, particularly for the 30 arcsec resolution.

2. We could use `getData` from the `dismo` package, but this will only work for resolutions **other than** 30 arcsec.

3. We could provide two options - user inputs their own local worldclim data or use the coarser resolutions from (2). 

Let me know what you think.

**Comment by BrunoVilela** [comment]
I think the best option for now, would be to use the getdata, even without the 30 arcsec... or even just upload the rasterstack for 10min... just to be sure it works for now.

**Comment by mlammens** [comment]
So far I've just moved (back) to using `getData`. We can add functionality for uploading later.

**Comment by ndimhypervol** [comment]
I think this issue is cleared, as we download the rasters via getData.
