### ISSUE TITLE
spThin doesn't retain correct rownames after remove point

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#13]
Test it by removing point 2, then running spThin. The output will include a point with the rowname of 2, even though the input did not have a 2. Does it rename the rownames internally?

**Comment by mlammens** [comment]
I'm pretty sure spThin renames the rows before the thinning process. spThin starts by making a new matrix of lat/lon coords, and I'm almost certain it does not retain the original row names. It's definitely the case that those removed points are not showing back up again.

**Comment by ndimhypervol** [comment]
I wasn't worried that the points were showing up again, only that the user would be unable to reference points that were dropped via the row names. If this is not a significant issue, let's not worry about it. Otherwise, we could always change spThin to retain the names if it's not too much trouble.

**Comment by mlammens** [comment]
Let's table this for now, and return to it later.
