### ISSUE TITLE
ENMeval not populating OR10 columns, sometimes

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#15]
For some runs, these columns were not getting populated (specific settings: search for "martes americana", then thin by 25km, then choose L, LQ and RM between 1:2 by 1). Is it due to the lack of rows in the table? Or something more mysterious? I commented out the final plot just to make the plotting work. Can someone look into this?

**Comment by ndimhypervol** [comment]
Forgot to add: resolution 10arcmin, MCP extent.

**Comment by ndimhypervol** [comment]
Just tried with expanded RMs and the results table is still lacking OR10. I am baffled.

**Comment by bobmuscarella** [comment]
I'm can't replicate this because I still can't get ENMeval to run (issue #11).

**Comment by mlammens** [comment]
@bobmuscarella I just pushed a version that should let you start ENMeval, but is still having problems. New bug I think.

**Comment by bobmuscarella** [comment]
We have to delete "updateProgress = updateProgress" from the arguments of the ENMevaluate function (not sure where it belongs?).    WHen I do that it at least runs.

But running with this deleted does seem to give the empty OR10 columns in the results table.  It is very strange because I just tried running the same analysis in my "normal R" session and it gave the OR10 columns without issue...

**Comment by ndimhypervol** [comment]
Installing the "edits" version of ENMeval will fix this. Don't delete the updateProgress parameter because then the progress bar won't function.

**Comment by mlammens** [comment]
How do you install the edits version?

**Comment by mlammens** [comment]
Interesting. I was able to replicate the error using your exact params. But I didn't have a problem when I used Protea repens.

**Comment by ndimhypervol** [comment]
Bob, can you weigh in? Maybe you will have a better idea why we are seeing this.

**Comment by bobmuscarella** [comment]
I have also seen that testing with the "martes americana" data.  I downloaded the same data and ran it locally and it came out fine (i.e., OR10 columns were included).  I will try the same with "Protea repens" and see what happens...

A shot in the dark: These columns are the only ones with numbers in the column headings... i don't see why that should be an issue but...

**Comment by ndimhypervol** [comment]
Okay, keep us updated! If it remains a mystery we can just pray no one downloads martes americana =D

**Comment by bobmuscarella** [comment]
I tried with Protea repens and several other species but I never got anything in the OR10 columns.  I have no idea why.

**Comment by ndimhypervol** [comment]
Crap, we should look into this. So, from what we understand, this is something weird that Shiny is doing, and not some new problem with ENMeval, right? Perhaps something goes wrong in the rendering of the table? Have you tried the download feature and checked to see if the columns are null in the hard data too?

**Comment by bobmuscarella** [comment]
Yes, I downloaded the table and it has NAs for the OR10 columns.

**Comment by mlammens** [comment]
Perhaps you all fixed this while I was driving home, when I just tried this with protea repens I **did** get results fo OR10

**Comment by ndimhypervol** [comment]
Problem solved -- there were sometimes NA env values for locs. It took some investigative work. I wrote a step that removes them, and BINGO -- OR10 outputs just fine.

**Comment by bobmuscarella** [comment]
This line needs to be un-commented out so the OR10 values get included in the evaluation plot:

#eval.plot(values$evalTbl, legend=FALSE, value="Mean.OR10", variance="Var.OR10")

(sorry, I wasn't sure of the best way to mention this...)

**Comment by ndimhypervol** [comment]
Done and done.
