### ISSUE TITLE
Progress messages

### ISSUE THREAD

**Issue by bobmuscarella** [ndimhypervol/wallace#18]
Regarding the progress messages in top right corner:
1) It'd be great if they were more noticeable (red background?)
2) It'd be very great if there were a progress bar that gave some indication of how long it's going to take to complete an analysis.  If the user is doing something that will take awhile they may think the program has frozen or something.

**Comment by ndimhypervol** [comment]
Yes, there are better (and more complicated) progress bar options, and if someone wants to experiment implementing them I think it would look a lot better! The "edits" version of ENMeval takes a progressBar object, so things should be relatively customizable.
