### ISSUE TITLE
Error ENMval

### ISSUE THREAD

**Issue by BrunoVilela** [ndimhypervol/wallace#21]
Hi guys, I always get this error while trying to use the ENMval:

unused argument (updateProgress = updateProgress)
'x' and 'y' lengths differ

**Comment by bobmuscarella** [comment]
Hey Bruno, this is addressed in issue #19 - the "updateProgress" argument in the ENMevaluate function call is only valid for an updated version of the package that you have to install from the ENMeval 'edits' repo (look at issue #19 for the line of code to do that).  Then it should essentially work although we're still having other issues with it (e.g. issues #15, #20)
