### ISSUE TITLE
leaflet for mapping

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#22]
If someone has time / interest:

I know we may not have time for this, but the leaflet maps are functional google-style maps with zoom and pop-ups --- so much better than our static image. All we need now is something who can figure out how to make it work for WALLACE! Here's the reference page for someone on the shiny team who wrote some scripts to make leaflet talk to shiny better: https://github.com/jcheng5/leaflet-shiny

**Comment by ndimhypervol** [comment]
Oh, and I started a branch for it.

**Comment by ndimhypervol** [comment]
Bruno, any progress on this?

**Comment by BrunoVilela** [comment]
Hi guys, a lot of progress, today I may commit it (it became very cool!!)

**Comment by ndimhypervol** [comment]
Sweet! Can't wait to see it. I assume we now have zoom functionality?

**Comment by BrunoVilela** [comment]
Yeah, look I will commit the first tow maps, I am working on the one to add the polygon, maybe you can help me on this one.

**Comment by BrunoVilela** [comment]
Hi guys, I commit the map changes.
You will note that they are only in the two first table panels (I am working on the one to add the polygons). Now the ID of the occurrence is given by clicking on the point.

Also you will need to install the package through github:
library(devtools)
install_github("leaflet-shiny", "jcheng5")
install_github("rCharts", "ramnathv", ref = "dev")

Please, provide me some feedback on this, so we can improve it.

**Comment by BrunoVilela** [comment]
Last map done!

**Comment by bobmuscarella** [comment]
Hey Bruno - I tried but I get errors when i try to install the package through github and then when I try to do runApp() i get: ERROR: could not find function "leafletMap" on the browser page.  I'm not sure what's pertinent so I am just pasting it all below:

> library(devtools)
> install_github("leaflet-shiny", "jcheng5")
Downloading github repo jcheng5/leaflet-shiny@master
Installing leaflet
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/dk/dkFa2BqoH301rMcPKLVo4U+++TI/-Tmp-/Rtmpui1rlQ/devtools24013cb1ecb4/jcheng5-leaflet-shiny-33efb48'  \
  --library='/Users/Bob/Library/R/3.1/library' --install-tests 
* installing *source* package ‘leaflet’ ...
** R
** data
** inst
** preparing package for lazy loading
** help
No man pages found in package  ‘leaflet’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (leaflet)
Warning message:
Username parameter is deprecated. Please use jcheng5/leaflet-shiny 
> install_github("rCharts", "ramnathv", ref = "dev")
Downloading github repo ramnathv/rCharts@dev
Installing rCharts
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/dk/dkFa2BqoH301rMcPKLVo4U+++TI/-Tmp-/Rtmpui1rlQ/devtools240119947075/ramnathv-rCharts-8d3fe35'  \
  --library='/Users/Bob/Library/R/3.1/library' --install-tests 

* installing *source* package ‘rCharts’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(name) : there is no package called ‘base64enc’
Error : unable to load R code in package ‘rCharts’
ERROR: lazy loading failed for package ‘rCharts’
* removing ‘/Users/Bob/Library/R/3.1/library/rCharts’
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use ramnathv/rCharts

**Comment by ndimhypervol** [comment]
I think just doing install.packages("leaflet") installs the same one Bruno wrote, but this is the newer version. I also couldn't install rCharts, but my maps loaded beautifully. Very well done, Bruno! It looks stunning. I'm glad you could make it look more professional.

**Comment by ndimhypervol** [comment]
If you do this, you should be able to load the maps:
devtools::install_github("rstudio/leaflet")

However, the functions we are currently using are deprecated, and at some point, we should upgrade to the more standard "leaflet" package syntax. But it works for now!

**Comment by ndimhypervol** [comment]
Hey Bruno --- I tried implementing the new syntax in the "leaflet" package, and it's a huge pain in the ass and there's no documentation to speak of, so I figure let's table that for when those clowns at RStudio get their act together. I wanted to try this because there's an easy way to add multiple point datasets to the same map in the new package, and I couldn't figure out how to do it with the deprecated functions. I'd like to plot the gbifoccs before spThin is called, then once it's called overlay the thinned points in a different color to show which were thinned and which not. Think we can do this? I tried to just throw two addCircle() calls, but it just wrote one...

**Comment by bobmuscarella** [comment]
Yes, this worked for the maps:
devtools::install_github("rstudio/leaflet")

**Comment by BrunoVilela** [comment]
I think, so I will work on this today

**Comment by ndimhypervol** [comment]
There is also the matter of leaflet-izing the last tab that plots the rasters. That's the first priority, I think.

**Comment by BrunoVilela** [comment]
This I think it will be quite complicated, as the leaflet map do not have an option to add a raster.... what we may need to do, if we really want to use it, is to: 

1) transform the raster into a polygon (grid like)
2) transform this polygon into the format used by the addPolygon function (it would require create a function to do it, do not know if it will be difficult).
3) then generate the map would be easy.

I can work on a function that make the 2 first steps, but this may turn the process slow for very high resolution, as polygons consumes much more memory than a raster.
After I will probably need your help, because I am not following the code after the 3th tab (although I can try to do it by myself).
what do you think? do we give a try?

**Comment by ndimhypervol** [comment]
Well, the new "leaflet" package has this functionality, apparently. Check out:
http://rstudio.github.io/leaflet/

It's just difficult for me to implement. Want to give it a try? If it doesn't work by this morning, we will have to take the video on the present version without raster leaflet mapping. When I tried just now to keep the rest of the code the same and drop in some new leaflet syntax just for the raster, the other leaflet maps wouldn't plot the points, etc. I am at my wit's end... Bruno, could you give it a try?

**Comment by BrunoVilela** [comment]
OK i will try ... But no warranties it will work. Do you need it for today, no?
