### ISSUE TITLE
pesky things

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#24]
1. When plotting the raster on the last tab, a little error pops up then disappears. Can we figure out how to get rid of it? It's: Error in `colnames<-`(`*tmp*`, value = "NULL.") : 
  length of 'dimnames' [2] not equal to array extent

2. If anyone's good with the ggplot, can you make our rasters look better? Couldn't figure out how to make a multi-color ramp for the scale, and settled for gray to blue. Looks drab. Can we emulate the default plot for rasters in ggplot?

**Comment by bobmuscarella** [comment]
Is it possible that the problem of #1 has to do with the fact that we save an object to 'e' in both the ENMevaluate step and when you set the extent in the plotMap function?

e <- ENMevaluate(values$df[,2:3], preds, bg.coords = backg_pts, RMvalues = rms, fc = input$fcs, 
                       method = input$method, updateProgress = updateProgress)
e <- extent(pred)

**Comment by bobmuscarella** [comment]
By the way, I am still not able to see the prediction rasters plotted.  I get two errors:

Error in `colnames<-`(`*tmp*`, value = "NULL.") : 
  length of 'dimnames' [2] not equal to array extent

Error in e[1] : object of type 'S4' is not subsettable

**Comment by ndimhypervol** [comment]
Yes, I'm getting the same errors, but my maps plot. Can everyone else try this and investigate please? The naming of "e" twice won't be an issue because there is no scoping conflict if we define it two different ways in different functions.

**Comment by bobmuscarella** [comment]
Now the maps are working for me but when I try to run ENMeval I get this error right away and everything stops:
Error : is.character(txt) is not TRUE

**Comment by ndimhypervol** [comment]
Would you be able to Skype sometime today, Bob? I'd like to try to work out your errors so we can get this working on all machines, even Danish ones.

**Comment by bobmuscarella** [comment]
sure - in a couple of hours work for you?

**Comment by ndimhypervol** [comment]
Shoot, sorry Bob. Got caught up in the lab. Is it nighttime there already?

**Comment by bobmuscarella** [comment]
Hey man, no problem.  Can we try tomorrow? Anyway, it's not a huge deal for
now as long as it's working for you.

**Comment by ndimhypervol** [comment]
Yes, sure thing. Current problem: got the app running online, but maxent crashes because there is no maxent.jar in the dismo/java folder server-side, and I don't know how to put it there...

**Comment by BrunoVilela** [comment]
Hi guys, maybe we can solve this problem by change the path the function looks for maxent; add maxent in one of our on folders and make this the path.

More exactly the function ".getMeVersion" that is used inside the maxent function (shown bellow).


.getMeVersion <- function() {

#HERE_THE_NECESSARY_CHANGE
	jar <- paste(system.file(package="dismo"), "/java/maxent.jar", sep='') 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	if (!file.exists(jar)) {
		stop('file missing:\n', jar, '.\nPlease download it here: http://www.cs.princeton.edu/~schapire/maxent/')
	}
	.rJava()
	mxe <- rJava::.jnew("meversion") 
	v <- try(rJava::.jcall(mxe, "S", "meversion") )
	if (class(v) == 'try-error') {
		stop('"dismo" needs a more recent version of Maxent (3.3.3b or later) \nPlease download it here: http://www.cs.princeton.edu/~schapire/maxent/
		\n and put it in this folder:\n',
		system.file("java", package="dismo"))
	} else if (v == '3.3.3a') { 
		stop("please update your maxent program to version 3.3.3b or later. This version is no longer supported. \nYou can download it here: http://www.cs.princeton.edu/~schapire/maxent/'")
	}
	return(v)
}

**Comment by mlammens** [comment]
Hi Bruno - I just sent an email to Jamie with the same idea! I think he's teaching most of the day, but hopefully will have time to try this later.

**Comment by ndimhypervol** [comment]
I actually tried this hack, but it didn't seem to work. Those mysterious Java functions somehow pull the Maxent version without accessing the "jar" filepath. In other words, the path is only part of the reference.

**Comment by ndimhypervol** [comment]
Can someone try to fix the initial issue I had with the dimnames today? The app would look a lot better if that was cleared up.

**Comment by ndimhypervol** [comment]
Apparently, this is an internal plotting issue with the newest raster package releases that is fixed if you use older versions. I tried this and I had a new issue with talking to the latest dismo version, so I give up trying to remedy this. I wonder if there's a way to mask this error via a validate()....

**Comment by ndimhypervol** [comment]
btw, Bruno, thanks a ton for the scale bar fix --- looks much better!
