### ISSUE TITLE
maxent loaded from folder

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#25]
Hey folks, can you try to get wallace to function using the modified maxent.R and JAR file in the same directory? If we can get this to work, I think the website may work too.

**Comment by mlammens** [comment]
I'll give it a go

**Comment by mlammens** [comment]
I can't get the app to deploy :(

**Comment by ndimhypervol** [comment]
shinyapps.io is not our friend. Thanks for the quick UCONN server hack, Matt!
