### ISSUE TITLE
for dev

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#26]
Let's add to this as we think things up:

1. convert data.frame rendering to datatables (package DT)
2. update leaflet syntax and get raster plotting to work

**Comment by ndimhypervol** [comment]
So I finally am getting back to Wallace, and I accidentally deleted the branches... I don't think anything that advanced was on them anyway. I was trying to get rid of the enormous pack files in the .git folder that contained all the rasters we uploaded a while back. When I cloned the repo today, it was 190 MB, and that got me started on trying to clean the pack files. I did succeed, but rendered the branches empty somehow... classic n00b. Hope no one's mad at me. I think we inserted most of what we wanted into master anyway.

I was thinking that if you haven't already pulled, you could locally switch to those branches, copy the two .R files, remake the branches, and recommit them. That would save the files if it worked. Could someone try that? I already made a new branch, but just ignore it.

**Comment by ndimhypervol** [comment]
Sorry if you got a message about me deleting branches everyone -- I just fixed it. So nothing happened. Nothing at all. I am now getting back into Wallace, so expect to hear from me a little more often. Is anyone else in a place to do a little dev?

**Comment by mlammens** [comment]
In less than a week I can carve out some dev time.
