### ISSUE TITLE
round 2

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#30]
This will be a running list of things that need to be done, and things that we accomplish that we want the group to know about:

Need To Do:
1) Image plotting doesn't seem to be available in leaflet yet. I asked about it today and will find out soon. We might be stuck with a static map unless we do Bruno's idea of converting to points and symbolizing them as markers with continuous colors.
2) I implemented datatables, and it looks a lot better, but the ENMeval output has too many columns and they increase the page width, which is annoying. I found a cool extension called "fixedColumns", but it erases the page scroller that allows you to see the rest of the records. I left it as is, but commented the extra extension code in case we figure out how to fix it.
3) Lots of user inputs need to be coded. I think we want to make as much downloadable as possible?
4) I started building a textbox on top of the map that acts like a log, recording messages throughout, and I'd like to make it available for download as a txt file. We can talk about this... I think it's more elegant than just throwing up text on the screen.

What I've done:
1) Condensed code, updated new leaflet and shiny syntax, changed the interface a bit.
2) Made everything plot to the same map. This is key to simplicity!
3) The thinned points now plot on top of the gbif ones, and I made them a different color to show what's been thinned, and what's been kept.

There's lots more to be done, and this doesn't include the stuff Rob and Bruno had in mind. We can hash out a plan when we finally talk together.

**Comment by ndimhypervol** [comment]
There is now raster plotting functionality in leaflet in the "newLeaflet" branch! Joe Cheng (one of the guys who builds shiny) pointed me to a dev branch on the shiny github page where he's been making these additions. They haven't been pulled to master yet, so there may be some more changes in the future.

**Comment by mlammens** [comment]
@ndimhypervol I think it would actually be easier to break out each of the todos as it's own issue. If someone gives my a +1, I'll go ahead and do that.

**Comment by ndimhypervol** [comment]
<@ndimhypervol gave @mlammens +1 spell power to help break todos into separate issues>
Thanks!

**Comment by mlammens** [comment]
@ndimhypervol do I have to role a die to see if I'm successful?

Kidding aside, I'll break things out a bit tomorrow, and maybe even assign some tasks to myself!

**Comment by ndimhypervol** [comment]
Okay, cool. Relieved that someone got my nerd joke.

**Comment by mlammens** [comment]
Separated these out into their own issues.
