### ISSUE TITLE
ENMeval output with datatables

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#32]
From @ndimhypervol  - I implemented datatables, and it looks a lot better, but the ENMeval output has too many columns and they increase the page width, which is annoying. I found a cool extension called "fixedColumns", but it erases the page scroller that allows you to see the rest of the records. I left it as is, but commented the extra extension code in case we figure out how to fix it.

**Comment by ndimhypervol** [comment]
Still an issue. Would someone want to take a look at it? I'm putting this off because it's a minor issue.
