### ISSUE TITLE
Textbox log

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#34]
From @ndimhypervol  - "building a textbox on top of the map that acts like a log, recording messages throughout, and I'd like to make it available for download as a txt file. We can talk about this... I think it's more elegant than just throwing up text on the screen."

**Comment by ndimhypervol** [comment]
If anyone is good with the CSS, please take a look at my crappy text container in newLeaflet and fix it! I beg you.

**Comment by ndimhypervol** [comment]
I "fixed" it by just taking the title "LOG" out of the box and putting it on top. Now it can't interfere with the text inside. Problem fixed.
