### ISSUE TITLE
Allow users to use own rasters

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#37]
Probably through dropbox links or something like that

**Comment by ndimhypervol** [comment]
Wrote a skeleton of this -- check it out in the new "round2" branch. I checked, and doing this with .asc files works fine, but we need to ask a lot of the user, like the CRS and the x- and y-dims. But it works. Just need to add the rest of the functionality in.

**Comment by mlammens** [comment]
@ndimhypervol Can we close this issue at this point?

**Comment by ndimhypervol** [comment]
Agreed. Let's put this away for the future.
