### ISSUE TITLE
Wallace broken with latest ENMeval changes

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#41]
Wallace isn't working since the most recent changes to ENMeval. Here's the error message we're getting:

Installing ENMeval
'/usr/lib/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/Rtmp4QDLw0/devtools4186169c60b/bobmuscarella-ENMeval-9fcec34'  \
  --library='/home/shiny/R/x86_64-pc-linux-gnu-library/3.1' --install-tests 

* installing *source* package ‘ENMeval’ ...
** R
** data
** inst
** preparing package for lazy loading
Error in parse(nsFile, srcfile = NULL) : 2:17: unexpected '[['
1: import("dismo", "methods", "rJava", "raster”, “doParallel”)
2: exportPattern("^[[
                   ^
ERROR: lazy loading failed for package ‘ENMeval’
* removing ‘/home/shiny/R/x86_64-pc-linux-gnu-library/3.1/ENMeval’
* restoring previous ‘/home/shiny/R/x86_64-pc-linux-gnu-library/3.1/ENMeval’
Error : Command failed (1)

**Comment by ndimhypervol** [comment]
Sorry... just did some dev on ENMeval and forgot we were pulling the github version for Wallace. I reverted my new edits and copied them into a different branch. This problem should have disappeared.
