### ISSUE TITLE
text box needs fixing -- Bruno?

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#43]
Hey folks, the text box to contain the log I made is not allowing you to scroll up and see the rest of the logs from before. I don't know CSS very well, and this is kind of the limits of my knowledge. Bruno, could you take a look?

**Comment by BrunoVilela** [comment]
Ok I will check it.

**Comment by BrunoVilela** [comment]
Problem solved. It was due to a fixed positioning of the text (it should be flexible), but if you just remove it, the scrollbox works. I also added a java script for automatic scroll the box when it is updated. Let me know if something goes wrong with it.

**Comment by ndimhypervol** [comment]
Bruno, you are the man. Knew I could count on you! I'll check this out later.

**Comment by ndimhypervol** [comment]
Works like a charm. Obrigado!
