### ISSUE TITLE
Some issues I found 

### ISSUE THREAD

**Issue by BrunoVilela** [ndimhypervol/wallace#44]
Just to let you know some small things I found that could make Wallace better:

1) The log file does not register the polygon selected points;
2) We should have a button to restart the analysis;
3) We need a scale bar on the last plot;
4) Some stuff make Wallace break, e.g. select the polygon background before the variables. We could implement some control to avoid this.

I will try to solve some of these issues, but if someone is doing something similar let me know.

**Comment by ndimhypervol** [comment]
Bruno, what do you mean by number 1? Do you think it'd be good to have the log report the selected point IDs? Yesterday I added log text for selecting and erasing via polygon. Would this be sufficient?

**Comment by BrunoVilela** [comment]
Ah perfect, that's exactly what you did. Thanks. To register how many points were erased by the polygon.

**Comment by ndimhypervol** [comment]
I'm working on adding legends to the maps, one of which will be a scale bar for the rasters.

**Comment by ndimhypervol** [comment]
Another issue: I reworked the behavior for the differential plotting of the tabs, but one pesky thing remains. If you don't select with polygon in tab1, get to tab3 and make an MCP or BB, then return to tab1, the MCP disappears like it should, but if you then make a selection it returns. Not sure why. Can someone fix this?

**Comment by ndimhypervol** [comment]
I added legends to all maps, but the raster scale is wrong, and not sure why...

**Comment by ndimhypervol** [comment]
@BrunoVilela, can you explain your #2? You can restart the analysis by going back to tab 1. Back-functionality should work. Can I also ask you to try and fix the scale bar for the raster output (just raw continuous -- the new thresholded rasters don't seem to have a problem), and your #4?

**Comment by BrunoVilela** [comment]
Hey Jamie, ok I will work on this. This week I will be more available to work more on Wallace. I think the 4th problem is the biggest one, I will try to fix all the things that make Wallace break (at least the ones I found). I though that maybe would be good if we have a button at any step that just clean everything and restart the software.

**Comment by ndimhypervol** [comment]
One more issue: the shapefile user input for background selection does not respond to the buffer number entered. It doesn't buffer. The CSV one does now though. Can someone look into this? I'm banging my head against the wall.

**Comment by ndimhypervol** [comment]
And yet another -- Bruno, if you have time, could you fix the HTML formatting on the ABOUT page? I am terrible at this stuff. Thanks!

**Comment by BrunoVilela** [comment]
Changed a bit the about... I think it is better now.

**Comment by ndimhypervol** [comment]
Yes, looks great! Only one problem -- The CCNY logo for RPA seems to fall below the other logo, and is not lined up like mine are. Is this just my screen?

**Comment by ndimhypervol** [comment]
Hey Mr. Fix-it, can you help me correct the raster scale bars to represent the raster values? The raw prediction raster scale bars are sometimes wrong (all 0.1's, etc.) and I can't figure out why. Thanks!

**Comment by BrunoVilela** [comment]
On my screen works fine, maybe it is dependent  :( ... I will check the raster

**Comment by BrunoVilela** [comment]
I will see the prediction visualization problem tomorrow, ok? I need to pass a couple of hours without see a code in front of me!

**Comment by ndimhypervol** [comment]
Yes, we are on the same page... I'll be dreaming in RStudio tonight.

On 1 September 2015 at 16:46, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> I will see the prediction visualization problem tomorrow, ok? I need to
> pass a couple of hours without see a code in front of me!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/44#issuecomment-136856116>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by ndimhypervol** [comment]
Hey Bruno, if you get to this -- the text doesn't line up with the photos on the About tab on my screen. Does it for yours? If it's a quick fix, could you align them better? Thanks!

**Comment by BrunoVilela** [comment]
In my screen looks fine... I think that it must be more strict somehow (like insert the texts and figures in a table) I will check it now

**Comment by ndimhypervol** [comment]
OK, thanks. Yeah, I'm thinking maybe the values that are going to the
legend are fine, but the display needs to change for the raw predictions.
They are too small, so we just get 0.0000, 0.0000, 0.0001, etc. Perhaps
changing them to scientific notation would be better. Can you figure out
how to do that? I think it's a parameter you can alter in the legend.

On 2 September 2015 at 10:17, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> In my screen looks fine... I think that it must be more strict somehow
> (like insert the texts and figures in a table) I will check it now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/44#issuecomment-137097207>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by BrunoVilela** [comment]
Ah look, I just noticed that the code for Minimum Training Omission in Bioclim is missing... I am looking the raster now

**Comment by ndimhypervol** [comment]
Bruno, can I close this issue?

**Comment by BrunoVilela** [comment]
Yep
