### ISSUE TITLE
Add source column to GBIF results?

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#47]
Perhaps we can add a column from the GBIF results on the data source. This helps address communications to Audience 2: Data Holders.

**Comment by ndimhypervol** [comment]
We currently have the field "basisOfRecord" which informs about the kind of data point (museum record, sighting, etc.) Which field were you thinking of including?

**Comment by mlammens** [comment]
I was thinking of the field that identifies the data provider (i.e., the museum or collection)

**Comment by ndimhypervol** [comment]
How does "institutionCode" sound? Unless there's a more appropriate one.

On 31 August 2015 at 22:03, Matthew Aiello-Lammens <notifications@github.com
> wrote:

> I was thinking of the field that identifies the data provider (i.e., the
> museum or collection)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/47#issuecomment-136550279>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by mlammens** [comment]
Should work for now.
