### ISSUE TITLE
knit Rmd to PDF

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#48]
I just had the greatest trouble knitting to a PDF on my mac (running yosemite), and still haven't gotten it resolved. Apparently, I need MacTex, which I guess didn't come with my OS? It's really big (2.5 gb), and I'm wondering if you also need it on the server side. The functionality is there for the pdf download, so Matt, could you try it and see if it works?

**Comment by BrunoVilela** [comment]
I am working on it

**Comment by ndimhypervol** [comment]
Thanks buddy. It looks like this might be a major dependency issue, and we can just elect to output a nice little HTML instead.

**Comment by BrunoVilela** [comment]
OK I added there the options for html and for word too... can you check if it works for you?

**Comment by BrunoVilela** [comment]
Just commited

**Comment by BrunoVilela** [comment]
check this: http://shiny.rstudio.com/gallery/download-knitr-reports.html

**Comment by mlammens** [comment]
I can see if this works server side later this afternoon, but given that it's a linux machine, latex is already there. I'm not sure how the word compilation will go though.

**Comment by mlammens** [comment]
@ndimhypervol Right - you need some version of Tex for knitr to work for PDFs. Forgot about that - sorry.

**Comment by ndimhypervol** [comment]
Well, I don't want to install the 5 gb monster that is MacTex right now, but if it works for you guys and the server, I am happy. Thanks Bruno!

**Comment by mlammens** [comment]
The Rmd knits to html just fine, but I have to trouble shoot to pdf in the AM. Other functionality seems to be pretty good on the server.

**Comment by mlammens** [comment]
Good news! PDF on the server side works.

**Comment by ndimhypervol** [comment]
YAY

On 3 September 2015 at 00:19, Matthew Aiello-Lammens <
notifications@github.com> wrote:

> Closed #48 <https://github.com/ndimhypervol/wallace/issues/48>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/48#event-399675040>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
