### ISSUE TITLE
need someone to review Rmd

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#49]
Hello. We need someone who is not Bruno to review his wonderful markdown file for textual inconsistencies, spelling / grammar, etc. Bob, would you be able to take a look? Or Matt. I would, but I am drowning in edits right now. Thanks!

**Comment by bobmuscarella** [comment]
I'm working on some suggestions for this...  get back to you soon...

**Comment by bobmuscarella** [comment]
###### *Here are my detailed comments (opinions!) for the markdown document.  Take what you like and chime in with differences of opinions.  Let me know if I can clarify anything...*

### **Main comments**
1) Move the **About** section to the very end in a separate section titled, **About this Document**.  (The current description of Markdown isn't that relevant).  The first section should be dynamically-titled with the same name used for the .html file.  The first section could be, for example:
>**Wallace Run [run name/date]**
This document provides a log of the R code used in the web app Wallace during [run name].  With this document, users can track their analysis, share it, and recreate it in R.

2) Include Rob's brief descriptions of each tab as text under each of the main section headings.

3) Include the code used to make the plots.

### **Line by line comments**
#### **Packages instalation** Section:
- Change the heading **Packages instalation** to **Package installation**

- Change the next line to: 
>Wallace uses the following R packages that need to be installed before starting:

- Change "Wallace also includes some functions..." to:
>Wallace also includes several functions developed to help integrate different packages and
some additional small functionalities.  For this reason, it is necessary to load the file
"functions.R", which can be found on Wallace's GitHub page (https://github.com/ndimhypervol/wallace). Download the file, place it in your
working directory ( use* `getwd()`*), and then load it:

#### **Obtain Occurrence Records** Section:
- Change "The search of occurrences will be limited to:" to:
>The search of occurrences will be limited to the user-specified number of records:

- Change "Apply the function to obtain the gbif records for the selected species:" to:
>The following command obtains occurrence records of the selected species from GBIF:

- Why does the name of the original results object need to be changed? Can we simplify by just calling the original results 'gbifOrig' in the first place?

- Change "Occurrence table changes:" to:
>Change the named of the occurrence record table:

- I don't understand what all is going on in the "Adjusting table values:" subsection.  This should have a more clear annotation.  Perhaps it should say:
>Adjust the formatting of the results table

#### **Obtain Environmental Data** Section:
- Change "Resolution of worldclim data:" to:
>User-selected resolution of WorldClim (http://www.worldclim.org/) data to use:

- Change "Remove occurrence records without environmental data:" to:
>Remove occurrence records that have NA for environmental data

- Change "Mask environmental variables by the background:" to:
>Mask environmental variables by the bounding-box:

#### **Build and Evaluate Niche Model** Section:
- Change "Define regularization multipliers (RM)..." to:
>Define regularization multiplier (RM) values:

- Change "Define feature classes (flexibility of modeled response):" to:
>Define feature classes:

**Comment by BrunoVilela** [comment]
I will make the changes

**Comment by ndimhypervol** [comment]
Yeah, much appreciated Bob and Bruno! I'll take a look after Bruno's done and maybe make a few small edits myself.

**Comment by ndimhypervol** [comment]
Bruno, did you make all these changes? If not, let me know what you got up to and I'll try to tackle them.

**Comment by BrunoVilela** [comment]
To do list:
2) Include Rob's brief descriptions of each tab as text under each of the main section headings.
3) Include the code used to make the plots.
*I will work on the 3th one now*

**Comment by ndimhypervol** [comment]
OK, I'm working on the input user csv for step 1.

On 2 September 2015 at 22:37, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> To do list:
> 2) Include Rob's brief descriptions of each tab as text under each of the
> main section headings.
> 3) Include the code used to make the plots.
> *I will work on the 3th one now*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/49#issuecomment-137305000>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
