### ISSUE TITLE
It is just me or the map is not appearing?

### ISSUE THREAD

**Issue by BrunoVilela** [ndimhypervol/wallace#50]
Map vanished in some commit today...

**Comment by ndimhypervol** [comment]
Yes, I've removed it from the intro tab, but it *should* appear in most of
the other ones!

On 1 September 2015 at 13:42, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> Map vanished in some commit today...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/50>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by BrunoVilela** [comment]
At least at my computer it is the place of the map with the zomm but there is no map there... just gray...

**Comment by ndimhypervol** [comment]
WAIT! Sorry but I forgot to mention this. Download the latest dev version
of leaflet from github. The code should be at the top of server.R. Joe
Cheng just fixed a bug I pointed out. He's a great guy! Once you reinstall
you should see the map. Sorry about that.

On 1 September 2015 at 13:47, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> At least at my computer it is the place of the map with the zomm but there
> is no map there... just gray...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/50#issuecomment-136810012>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by BrunoVilela** [comment]
Great! Works now, thanks!

**Comment by ndimhypervol** [comment]
ALSO: make sure to reinstall ENMeval@edits -- I changed it to make logistic
predictions too.

On 1 September 2015 at 13:53, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> Closed #50 <https://github.com/ndimhypervol/wallace/issues/50>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/50#event-398092698>.
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
