### ISSUE TITLE
Night Issues

### ISSUE THREAD

**Issue by BrunoVilela** [ndimhypervol/wallace#51]
Hey guys... These are my first issues of the night:

1) I cannot upload my own data in the first section (can someone else try?), maybe provide me an example data.
2) In the prediction maps we have to remove the raster before plotting the next one... if you just plot once, it is ok, but if you try to plot more later, it overlays the old.

**Comment by BrunoVilela** [comment]
Hey guys again, the problem with the raw prediction of the maxent is that in my opinion it is not normalized...

**Comment by ndimhypervol** [comment]
Can you explain what you mean? Is this in reference to the legend?

On 2 September 2015 at 21:04, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> Hey guys again, the problem with the raw prediction of the maxent is that
> in my opinion it is not normalized...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/51#issuecomment-137290493>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by BrunoVilela** [comment]
The e@predictions.raw was not a normalized data as the reference in the legend says so... So I normalize the data now. But I want to be sure if is this what you really wanted...

**Comment by ndimhypervol** [comment]
We don't want them normalized, else they are not representative of the interpretation of the raw output (relative occurrence rate), so I took it out. Thanks for trying though. Maybe we can still get scientific notation in the legend?

**Comment by ndimhypervol** [comment]
I am finding that the ORmin and OR10 for BIOCLIM is identical. Is this normal, and may change with higher number of occs?

**Comment by BrunoVilela** [comment]
I just saw it... Probably there is some error there... but I couldn't find anything until now..

**Comment by ndimhypervol** [comment]
Maybe Bob will have a better idea.

**Comment by ndimhypervol** [comment]
I'm checking out for the night, but can someone check on the ORmin and OR10 for the Bioclim rasters and make sure that they are not always the same? Thanks!

**Comment by robertpanderson** [comment]
Hi all,

I think it is very likely that these two omission rates will be the same with small numbers of localities (e.g., less than 10).  If the pattern continues with more than 15 or 20 localities, I would worry though.

Rob



I am finding that the ORmin and OR10 for BIOCLIM is identical. Is this normal, and may change with higher number of occs?


*************************************
Robert P. Anderson, Ph.D.
Professor, Department of Biology
526 Marshak Science Building
City College of New York, City Univ. of New York
160 Convent Avenue
New York, NY 10031, USA

Telephone: (212) 650-8504
http://web.sci.ccny.cuny.edu/~anderson/
NOTE NEW E-MAIL: randerson@ccny.cuny.edu<mailto:randerson@ccny.cuny.edu>

**Comment by BrunoVilela** [comment]
I made some tests over the ORmin and OR10. The pattern continue even with many occurrence records. The origin of it is that many of the occurrence records have the smallest predictions values possible (more than 10%  of the values), so that's why they seem equal... What makes me suppose that there is no problem with the code, unless the prediction itself is wrong.

**Comment by ndimhypervol** [comment]
Great, Bruno. However, it's not clear to the average user. Should we
mention this in the text somewhere?

On 3 September 2015 at 12:12, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> I made some tests over the ORmin and OR10. The pattern continue even with
> many occurrence records. The origin of it is that many of the occurrence
> records have the smallest predictions values possible (more than 10% of the
> values), so that's why they seem equal... What makes me suppose that there
> is no problem with the code, unless the prediction itself is wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/51#issuecomment-137498838>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by BrunoVilela** [comment]
Maybe a small note on parenthesis to avoid confusions... We cannot say much also because it would need a more comprehensive test.

**Comment by BrunoVilela** [comment]
I liked the idea of the color buttons... did something went wrong?

**Comment by ndimhypervol** [comment]
Yes, I was reprimanded for my fancy color buttons. Too late for something like that - the video would have to be redone, etc. Maybe Wallace 0.3.

**Comment by BrunoVilela** [comment]
heheheh ok, no time for new stuff.... I am just fixing things I am seeing now... to include the plots in the .rmd would need a lot of new code (which means a lot of new bugs)... I though that it is better concentrate in what we already have.

**Comment by BrunoVilela** [comment]
Hi there.... the only bug still holding that I can see is the upload of user own datasets... at least in my pc

**Comment by BrunoVilela** [comment]
Also, use a polygon in shapefile format as background gives an error

**Comment by BrunoVilela** [comment]
I checked whether the sink to Rmd was the problem in uploading the data.... I removed all the sink code from the csv load and still get the same error...

**Comment by BrunoVilela** [comment]
with more tests, the problem is on the reading of the file itself

**Comment by ndimhypervol** [comment]
I removed the shapefile functionality completely because it was giving us
problems. The csv poly works fine now.

On 4 September 2015 at 08:57, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> with more tests, the problem is on the reading of the file itself
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/51#issuecomment-137728973>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
