### ISSUE TITLE
downloads for component 7

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#53]
Need download buttons for response curves (not done yet) and BIOCLIM graph.

**Comment by ndimhypervol** [comment]
Bruno, can you work on this?

**Comment by BrunoVilela** [comment]
ok I will do it

**Comment by ndimhypervol** [comment]
Thanks Bruno!

**Comment by BrunoVilela** [comment]
Hey Jamie, every time I try to see the prediction curves this error occurs
"attempt to select less than one element"

and for BIOCLIM envelop plots this other one:
"argument 2 matches multiple formal arguments"

are these part of the problem or is just on my pc?

**Comment by BrunoVilela** [comment]
Also..
1) any attempt to generate maxent models ended in error
2) the download button in component 1 gives me an empty csv file.

I want to clarify if these errors are just here (in this case I am doing something wrong locally) or if it is something general.

**Comment by ndimhypervol** [comment]
Are you on branch navBar?

**Comment by ndimhypervol** [comment]
These are not errors I experienced, but I'll look into it. I have yet to go through a full walkthrough, but I have been through much of the analysis recently.

**Comment by BrunoVilela** [comment]
Yeah, I am in navBar, I will keep checking if I got something wrong here. But maybe would be good to ask another person to check this also, as you may have something locally that does not give you these erros.

**Comment by ndimhypervol** [comment]
Bruno, so the first two problems are only with BIOCLIM. The response curves should work (I think) for BIOCLIM -- not sure why they don't, but they work for me when I run Maxent, except that they throw an initial error before it quickly disappears and works. Not sure why that happens. The BIOCLIM envelope plots have something wrong -- I can investigate. The Maxent eval plots should not register when the user makes a BIOCLIM model, and vice versa for the BIOCLIM plot. I just fixed the gbif occs download problem (careless change of name), but it now serves only the original gbif records after cleaning. It needs to serve this plus the ones the user adds with the user upload function. Not sure why Maxent wouldn't be working for you, because it works on my side. Update packages, maybe?

Thanks for the help, Bruno.

**Comment by BrunoVilela** [comment]
Yep, I needed to updated the packages... shame on me.
But still the as you noticed, the curves for BIOCLIM are not working. 
I will work on the buttons for the module 2 and 7, but I will take a look if I can fix the curves problems.
Thanks.

**Comment by ndimhypervol** [comment]
The BIOCLIM plots work on my end -- test out the latest commit and see if you're still having problems. I just fixed some other bugs, too, and will try to finish the project to new time section, and fill in some language for component 8 next.
