### ISSUE TITLE
block partition behaving funny

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#54]
Someone should take a closer look at this. Search for "heteromys anomalus" with 12 recs and do "block" partitioning. Doesn't look right.

**Comment by ndimhypervol** [comment]
Hey Bob, can you work on this if you have any time at all? The block partitioning in ENMeval is not working like I think it should.

**Comment by bobmuscarella** [comment]
Hej - 
Can you elaborate?  I just tried it and I don't see anything obviously wrong with it.  Check out this screen shot:
[block_HETANO_12.pdf](https://github.com/ndimhypervol/wallace/files/122763/block_HETANO_12.pdf)

**Comment by ndimhypervol** [comment]
Hm, maybe there is nothing wrong with it. I guess what threw me off is the
distance between the two purples, but that's just a function of the
latitudinal closeness? There shouldn't be an issue anyway, as this process
was vetted, but I thought I saw something weird.

On 9 February 2016 at 03:43, Bob Muscarella <notifications@github.com>
wrote:

> Hej -
> Can you elaborate? I just tried it and I don't see anything obviously
> wrong with it. Check out this screen shot:
> block_HETANO_12.pdf
> <https://github.com/ndimhypervol/wallace/files/122763/block_HETANO_12.pdf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/54#issuecomment-181762521>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC
