### ISSUE TITLE
projecting to new areas / times

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#56]
I'll be working on component 8, which projects. If anyone feels a great desire to help me, please let me know and we can carve out a work plan.

**Comment by robertpanderson** [comment]
All:
Just remember that this is a big addition!  Be sure you want to bite off and chew it now, rather than keep it as something that could be added in a grant proposal.
Rob

*************************************
Robert P. Anderson, Ph.D.
Professor, Department of Biology
526 Marshak Science Building
City College of New York, City Univ. of New York
160 Convent Avenue
New York, NY 10031, USA

Telephone: (212) 650-8504
http://www.andersonlab.ccny.cuny.edu/
randerson@ccny.cuny.edu<mailto:randerson@ccny.cuny.edu>

**Comment by BrunoVilela** [comment]
Jamie, congratulations for the updates in Wallace, the software looks awesome, I found no bugs until the 7th module. Also, the new design is super cool! 

However, I still found some issues, on the module 7 (I will try to fix these bugs):
- Error in plot curve predictions for bioclim.
- BIOCLIM Envelope Plots: for maxent indicates variable contribution (this should be in another sub-module), while it should be disabled when maxent is used.
- Maxent Evaluation Plots: Delta AICc error (object variance not found).

About the module 8, it is very nice and will be a great improvement to Wallace. Therefore, it is still in the very beginning. I believe we could do like Rob said, let this module under a new branch, which we could keep working while the manuscript is under review (maybe it could be a new improvement to say to the reviewers that Wallace is continuously growing or let it for a grant proposal as Rob said). I think we should finish this Wallace version with the module 7, fix all the bugs, and submit it as so. However, if you think we can do it fast enough, we can continue with it, but I believe that more bugs will show up and we don't want to lose the publication timing. What do you think?

**Comment by BrunoVilela** [comment]
Error in plot curve predictions for bioclim fixed.
Try to fix the other two I cited.

**Comment by BrunoVilela** [comment]
Hum... another thing I found, in module 5 an error occurs when I press the partition button without selecting the options first. It would be good to have this button disabled until all the options are selected (it happened twice with me today). Sorry for putting all the things in the same 'issue'... I will try to fix these things I am finding still today.

**Comment by BrunoVilela** [comment]
Error in BIOCLIM Envelope Plot when maxent is used fixed.

**Comment by bobmuscarella** [comment]
Hey Bruno -
I'm not sure if you fixed this yet but I *suspect* the "Maxent Evaluation
Plots: Delta AICc error (object variance not found)." problem is related to
the fact that you don't get a measure of variance with the AICc values.
 (i.e., as opposed to the evaluation stats based on cross-validation, you
only get 1 AICc value).  The default of the 'eval.plot' function sets
variance to NULL but this error sounds like the 'eval.plot' function may be
trying to put error bars on the AICc plot when this information doesn't
exist.  I hope that's more helpful than confusing but let me know if I can
clarify.

**Comment by BrunoVilela** [comment]
Thanks for the hint Bob, I was going to check this issue now, I will let you know what happened.

**Comment by BrunoVilela** [comment]
The issue with button in module 5 is fixed. In addition, I found that when we write species wrong names, an error occurs again... this issue was fixed in early versions, maybe it would be nice to reuse part of that code to avoid this problem.

**Comment by ndimhypervol** [comment]
Thanks, Bruno! I need to pull these changes and check out all the fixes.
Another urgent matter is making sure the R Markdown still works. It did
when I made my edits, but I tried it recently and something was wrong. If
it's too convoluted, I can take a look later.

On 29 February 2016 at 15:23, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> Thanks for the hint Bob, I was going to check this issue now, I will let
> you know what happened.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/56#issuecomment-190369486>
> .
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by BrunoVilela** [comment]
I got this issue with the R markdown code track: "cannot open the connection", but I got this error since before I start editing... I though I was making something wrong here, is it the same error you get?

**Comment by BrunoVilela** [comment]
The problem with the names seems to work fine now, without any changes here... maybe it just occurs in specific cases (e.g. after using some of the modules)

**Comment by ndimhypervol** [comment]
Everything looks like it works great! I tabled the MESS tool, but am leaving in the projection feature because I think it works the way it should (and it's a nice addition). One issue I found though -- I went through, modeled in Maxent, then looked at predictions. Fine. Then I went back and downloaded a new set of points, went through again, and found that Maxent ran really fast, output weird stats (lots of 0's), and the predictions looked funny. Restarted and redownloaded same number of points, no issue. I'm thinking it's a weird problem with the reference to the occ pts, or something else. Bruno, could you check this out? I will too and see if I find anything.

**Comment by ndimhypervol** [comment]
BTW -- fixed the AICc plotting issue by putting a `variance <- NULL` in an `else` clause to make sure it exists. Not sure why that didn't give us trouble before.

**Comment by ndimhypervol** [comment]
Also fixed some dumb var name errors in userReport.Rmd. I had shortened some names and forgot to change them in this file too.

**Comment by BrunoVilela** [comment]
Great Jamie, I will keep with the debug today, I will check the module 2 issue first.

**Comment by BrunoVilela** [comment]
I fixed the issue by adding a 'reset' function when you download or update occurrence data. So, every time you search for a species name, all data values are set to NULL. This avoids a lot of problems. What do you think?

> "One issue I found though -- I went through, modeled in Maxent, then looked at predictions. Fine. Then I went back and downloaded a new set of points, went through again, and found that Maxent ran really fast, output weird stats (lots of 0's), and the predictions looked funny. Restarted and redownloaded same number of points, no issue. I'm thinking it's a weird problem with the reference to the occ pts, or something else. Bruno, could you check this out?"

**Comment by BrunoVilela** [comment]
Hi guys, I have been working on the 8th component/module today. I think it is working now. It would be nice if someone could check it. Thanks.

**Comment by ndimhypervol** [comment]
Thanks, Bruno! I will take a look at it later tonight.

On 31 March 2016 at 15:58, Bruno Vilela de Moraes e Silva <
notifications@github.com> wrote:

> Hi guys, I have been working on the 8th component/module today. I think it
> is working now. It would be nice if someone could check it. Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ndimhypervol/wallace/issues/56#issuecomment-204102136>
>



-- 
Jamie Kass
PhD Student, Biology
Anderson Lab <http://web.sci.ccny.cuny.edu/~anderson/>, City College, NYC

**Comment by ndimhypervol** [comment]
Component 8 looks great -- thanks Bruno! I would like to use the MESS functionality, but perhaps that's a little too much for right now. We should be happy the product works. I am closing this issue.
