### ISSUE TITLE
comp 2 plotting behavior

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/wallace#57]
Just realized that if you spatial thin first, then select with polygon, the plotting messes up. This needs to be fixed.

**Comment by BrunoVilela** [comment]
I believe I fixed this issue now in the new commit. Can you check if the problem still occurs?

**Comment by ndimhypervol** [comment]
Thanks Bruno! I'll check later today. Doing a demonstration in RPA's class today. Hope Wallace behaves =]

**Comment by BrunoVilela** [comment]
Good lucky with that! So, until the component 7 all bugs seems to be solved (until new ones appear). What is need now? Do you want help in the 8th? or do you have another task in mind?
