### ISSUE TITLE
Cleaning the occurrence points

### ISSUE THREAD

**Issue by BrunoVilela** [ndimhypervol/wallace#7]
We really need to allow the users to remove manually some occurrences before thinning. Many occurrences are in the sea, we could insert an option to remove points from the ocean (maybe a checkbox).

**Comment by ndimhypervol** [comment]
Removing points in the ocean might take some time to implement -- we'd need to have a world map shapefile and then find points that intersect with ocean? Unless someone can pump that out fast... I do believe we should add the option of removing occurrences at duplicate localities.

**Comment by BrunoVilela** [comment]
What I am working right now is too manually remove the points instead of the ocean as Matt suggested me. Do you agree? remove duplicates would also be good.

**Comment by ndimhypervol** [comment]
Sure. Wondering how you're doing that? The user provides row names?

**Comment by BrunoVilela** [comment]
I am going to another way, the user would be able to click on the map and remove the points.

**Comment by bobmuscarella** [comment]
Also, don't forget, GBIF has sea creatures, too, so eliminating points that
fall in ocean isn't a fix for all users....

**Comment by ndimhypervol** [comment]
Closing this for now, with the acknowledgement that Bruno may have a functional update for us before the deadline.
