### ISSUE TITLE
Create separate tab for raster plotting

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/wallace#9]
We should create a new tab for plotting rasters. Are we only including worldclim right now?

**Comment by ndimhypervol** [comment]
Yes, only including worldclim for now but adding some grayed-out text showing we're thinking about other data inputs (e.g. climond, prism, user). I agree that tab 5 should be for raster plotting. Bob's ENMeval results graphs (which he sent me this morning) can go in the ENMeval tab.

**Comment by ndimhypervol** [comment]
Put this in.
